-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.admins
(
    login character varying(30) COLLATE pg_catalog."default" NOT NULL,
    senha character varying(30) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT pk_login PRIMARY KEY (login)
);

CREATE TABLE IF NOT EXISTS public.itens
(
    id_item serial NOT NULL,
    dono character varying(20) COLLATE pg_catalog."default",
    nome character varying(100) COLLATE pg_catalog."default",
    foto character varying(255) COLLATE pg_catalog."default",
    data_criacao date,
    nome_dono character varying(100) COLLATE pg_catalog."default"
);
END;